source 'https://github.com/WyICSP/WFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'WFBusSchool_Example' do
  pod 'WFBusSchool', :path => '../'

  target 'WFBusSchool_Tests' do
    inherit! :search_paths

    
  end
end
